#!/bin/sh

set -eu


basedir="$(readlink -f "$(dirname $0)")"
tmpdir="$basedir"/tmp
datadir="$tmpdir"/data
hostport=5000
#dockerimgname=seojikim/squad:production
dockerimgname=seojikim/squad:2019.09
mkdir -p "$datadir"

exec docker run \
  --env=XDG_DATA_HOME=/app/tmp/data \
  --publish=${hostport}:5000 \
  --volume="$basedir":/app \
  --rm \
  --name squad \
  -it ${dockerimgname} "$@"
